OBJS := Thread.o Condition.o async_logging.o log_file.o log_stream.o logging.o file_util.o process_info.o timestamp.o countdown_latch.o timezone.o date.o
DIRS := # FILL: subdirs contain src files

# NOTE: here should be SUB_MAKE_INCLUDE, different from the top Makefile
include $(SUB_MAKE_INCLUDE)