OBJS :=  Util.o Channel.o Epoll.o EventLoop.o Timer.o EventLoopThread.o EventLoopThreadPool.o Server.o Client.o
DIRS := # FILL: subdirs contain src files

# NOTE: here should be SUB_MAKE_INCLUDE, different from the top Makefile
include $(SUB_MAKE_INCLUDE)